[tool.poetry]
name = "hazard-scoring-service"
version = "1.0.0"
description = "Hazard Scoring Service for NER Logistics Platform"
authors = ["Dharmanshu"]
packages = [{ include = "stockflow_hazard", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.0"
uvicorn = "^0.23.2"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
httpx = "~0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
