export function generateReport(data) {
  const report = `
===============================
 CARBON ACCOUNTABILITY REPORT
===============================

Company : ${data.company}
Industry: ${data.industry}
Month   : ${data.month}

-------------------------------

Electricity : ${data.electricity} kWh
Fuel        : ${data.fuel} L
Transport   : ${data.transport} km
Waste       : ${data.waste} kg

-------------------------------

Total Emission

${data.total} kg CO₂e

===============================

Generated by
Carbon Accountability Platform

`;
  return report;
}