import {
  BrainCircuit,
  Leaf,
  Truck,
  PackageCheck,
  ArrowRight,
} from "lucide-react";

export default function QuickInsights({ data }) {
  if (!data) return null;

  const insights = [
    {
      icon: BrainCircuit,
      title: "AI Optimization",
      description:
        "AI recommends optimizing delivery routes to reduce travel time and operational cost.",
      color: "bg-violet-100 text-violet-600",
    },
    {
      icon: Leaf,
      title: "Carbon Reduction",
      description:
        "Estimated carbon emissions reduced by 12% compared to last month.",
      color: "bg-emerald-100 text-emerald-600",
    },
    {
      icon: Truck,
      title: "Fleet Status",
      description:
        "94% of fleet vehicles are active and operating efficiently.",
      color: "bg-blue-100 text-blue-600",
    },
    {
      icon: PackageCheck,
      title: "Inventory Health",
      description:
        "Warehouse inventory remains stable with no critical shortages detected.",
      color: "bg-orange-100 text-orange-600",
    },
  ];

  return (
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6">

      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">
            AI Insights
          </h2>

          <p className="text-slate-500 mt-1">
            Smart recommendations generated by StockFlow AI
          </p>
        </div>

        <div className="px-4 py-2 rounded-full bg-emerald-50 text-emerald-600 font-semibold">
          Live
        </div>
      </div>

      <div className="space-y-5">
        {insights.map((item, index) => {
          const Icon = item.icon;

          return (
            <div
              key={index}
              className="flex items-start justify-between p-5 rounded-2xl border border-slate-100 hover:border-emerald-300 hover:shadow-md transition-all duration-300"
            >
              <div className="flex gap-4">

                <div
                  className={`w-14 h-14 rounded-2xl flex items-center justify-center ${item.color}`}
                >
                  <Icon size={26} />
                </div>

                <div>
                  <h3 className="font-semibold text-lg text-slate-800">
                    {item.title}
                  </h3>

                  <p className="text-slate-500 mt-1 leading-relaxed">
                    {item.description}
                  </p>
                </div>

              </div>

              <ArrowRight
                size={20}
                className="text-slate-400 mt-2"
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}